### PR TITLE
Add dunder methods to Document class

### PR DESCRIPTION
**Pull request by djross22**
I've added __len__() and __str__() methods to the Document class.
Also added summary() and size() to match similar pySBOL2/Document methods.

### CODE REVIEW

**Comment by djross22** [comment]
Looks like my use of numpy didn't pass the checks.

Should I try to rewrite the code without numpy? Or can numpy be added as a dependency?

**Comment by djross22** [comment]
I rewrote the Document.summary() method using the built-in set() instead of numpy.unique().
Still fails the checks, but I can't tell why-

**Comment by djross22** [comment]
@tcmitchell - I cleaned up the pep8 style errors, so now this branch passes the checks. So, I think it's ready for you to look at it-

**Comment by tcmitchell** [comment]
@bbartley can you look this over?

As implemented here `len(my_document)` will return the number of top level objects in the Document. This count will not include child objects or orphans (unattached SBOL objects and non-SBOL objects). Is it useful to have this method? I think this is just being carried forward from pySBOL2 to support the getting started page, which itself is getting carried over from pySBOL2.

One of the reasons I didn't implement `__len__` or `__str__` is that I don't think either of the implementations from pySBOL2 is terribly useful. These are fine implementations to start with but to me they are also rather meaningless.

@bbartley @jakebeal what would be useful implementations of these methods for your work?

**Review by jakebeal — APPROVED** [review]

**Comment by bbartley** [comment]
@tcmitchell I don't have a strong opinion about the `__str__` method.  In fact, I can't even remember what this method did in pySBOL2.  However, I do think the `__len__` method comes in handy sometimes.  While I can't remember an exact use case, my general recollection is that it sometimes it comes in handy when checking if a `Document` is empty, integrating objects from multiple documents, or debugging a script.

**Comment by jakebeal** [comment]
The `__str__` method is a prettier encapsulation of an operation that I often do while debugging.
The `__len__` method is a macro for something I often do; I have no objection to shortening my code by a few characters.

**Pull request merged**
